### ISSUE TITLE
Want to be linked to nerfacc repo?

### ISSUE THREAD

**Issue by liruilong940607** [bennyguo/instant-nsr-pl#1]
Awesome job Yuanchen! I was thinking of doing an example in nerfacc with NeuS. But you already got it worked even with pytorch-lightning!!

Do you want to be linked to nerfacc repo for showcase?

BTW I noticed you are relying on alpha marching & rendering, which is currently from your fork of nerfacc. I just add this support in `nerfacc>=0.2.2`, along with relaxing the pytorch requirement. Check it out if interested! https://github.com/KAIR-BAIR/nerfacc/pull/94

**Comment by bennyguo** [comment]
Thanks Ruilong! That would be great!

I already update the dependency to your official nerfacc repo in the latest commit, cheers 🎉

**Comment by liruilong940607** [comment]
Linked! Great job again!

**Comment by Jiakui** [comment]
> 

Hi Ruilong, 

It looks for me that, although much faster,  the neus with hash encoding is much worse than the vallina MLP version neus (I tried both instant-nsr and instant-nsr-pl , they are both not as good as neus, so I guess  hash encoding should be responsible for the degradation of the reconstruction quality ) .  Do you have any idea why ?  

Thanks!
