### ISSUE TITLE
NeRF code seems not export mesh.

### ISSUE THREAD

**Issue by StarsTesla** [bennyguo/instant-nsr-pl#102]
Hi there, I clone the latest code, and I trained the nerf as the README, while after training, I check the dir of exp, and I found that ,the obj file shows nothing but:

![image](https://github.com/bennyguo/instant-nsr-pl/assets/45264423/4340c44b-3970-490d-a8a2-33ca3842a7db)
 
So I guess is there somthing wrong?

**Comment by StarsTesla** [comment]
I tried reduce the threshold to 0.1(old was 5.0) seems work, but noise shows everywhere(Lego), and 0.5 seems not work again, very strange.

**Comment by weihan1** [comment]
Hi, I'm facing the same issue, apparently it's because the level in the isosurface_ function contains NaNs. How did you end up solving this problem? Just by setting the threshold to 0.1?
