### ISSUE TITLE
RuntimeError: CUDA out of memory，How can I adjust the parameters to video memory consumption?

### ISSUE THREAD

**Issue by me714** [bennyguo/instant-nsr-pl#25]
When I train the model with 2160*3840 images I get the following error, how can I tweak the parameters to reduce the video memory consumption
![image](https://user-images.githubusercontent.com/73265048/205433934-cdbc094e-9134-410a-a398-90f111ca80e2.png)

**Comment by bennyguo** [comment]
The CUDA OOM error happens in the validation stage as the image rendered for visualization is too large. In the validation/testing stage, the pixels to be rendered are chunked into batches, fed to the network sequentially and merged together by a `chunk_batch` function: https://github.com/bennyguo/instant-nsr-pl/blob/6ab0c3d7e1db4973372b726a517d02bef6c8cf2a/models/nerf.py#L134
You could try modifying the `chunk_batch` function to move all the output tensors to CPU before merging.
