### ISSUE TITLE
Origin of magic constants within code

### ISSUE THREAD

**Issue by kzhang2** [bennyguo/instant-nsr-pl#42]
Hi,
Where does 1.732 * 2 come from from the below line? 
https://github.com/bennyguo/instant-nsr-pl/blob/6ab0c3d7e1db4973372b726a517d02bef6c8cf2a/models/neus.py#L58
I'm guessing that this is sqrt(3) * 2, but how was it derived?

**Comment by bennyguo** [comment]
Hi! This simply calculated the step size as `1 / self.config.num_samples_per_ray ` of the diagonal length of the bounding box :)
