### ISSUE TITLE
How to extract high resolution mesh

### ISSUE THREAD

**Issue by SarahWeiii** [bennyguo/instant-nsr-pl#46]
I was wondering if it is feasible to extract a mesh with very high resolution using the Marching Cube algorithm, say 2048**3? In theory, it shouldn't require excessive memory, but we seem to be encountering difficulties with both the CPU and GPU, resulting in cuda out of memory errors. Could you help us with this problem?

**Comment by bennyguo** [comment]
Building a 2048^32 float32 grid literally requires **32GB** memory. So the current version could not run on GPUs with less than 32GB memory. I tried using the CPU and found that the grid was first transferred to the GPU and then split as network input, which would cause CUDA OOM when the resolution is high. I fixed this issue in the latest commit. Thanks for reporting!

**Comment by bennyguo** [comment]
BTW, it could take a very long time to extract the surface if you set the resolution to larger values like 2048. If so, you may try increasing `model.isosurface.chunk` as long as the program fits in the GPU memory.

**Comment by SarahWeiii** [comment]
Thank you for the quick reply!
