### ISSUE TITLE
Minor issue

### ISSUE THREAD

**Issue by yyeboah** [bennyguo/instant-nsr-pl#63]
@bennyguo Kudos on how far you've brought this project since it's early stages. Indeed, performance has come an incredibly long way since the bug in issue #9 . Cheers. 

By the way going through the current version I noticed some minor issues in the ReadMe which I've fixed in this PR #62 . Another issue I'm looking into is that I noticed when optimizing a NeuS on DTU without mask, this line throws a data type error: https://github.com/bennyguo/instant-nsr-pl/blob/5927901771d49ef0e38f4125d818485d9bb4aeca/models/neus.py#L157

I haven't come around to resolving it yet but let me know if you've already caught it.

**Comment by bennyguo** [comment]
Could you post the full error message? Thanks!

**Comment by yyeboah** [comment]
Sure. So a scalar type double was expected, but a float was found. I solved this by casting the variable as a double. All is good on my end now. Weirdly, I noticed issue #66 is quite the opposite case :)

**Comment by aztsdfhj** [comment]
> 

Hello, I also encountered the same problem as you, can you tell me how you solved it, thank you very much

**Comment by bennyguo** [comment]
@aztsdfhj Please refer to https://github.com/bennyguo/instant-nsr-pl/commit/d834831a2a98b8647463dcbb26b1458aa51a3bcc. You may try adding back the `.double()` and see if it works.
