### ISSUE TITLE
ImportError: /home/anaconda3/envs/instant-nsr-pl/lib/python3.8/site-packages/tinycudann_bindings_61/_C.cpython-38-x86_64-linux-gnu.so: undefined symbol: _ZNK2at6Tensor6deviceEv

### ISSUE THREAD

**Issue by sunshineywz123** [bennyguo/instant-nsr-pl#7]
![企业微信截图_16677204873554](https://user-images.githubusercontent.com/32233542/200159812-4225b22d-5a65-48b2-b3de-cedbc627583d.png)
ImportError: /home/anaconda3/envs/instant-nsr-pl/lib/python3.8/site-packages/tinycudann_bindings_61/_C.cpython-38-x86_64-linux-gnu.so: undefined symbol: _ZNK2at6Tensor6deviceEv

I have this error, according to the readme operation down, google and issue did not find a similar problem, you have encountered there?

**Comment by bennyguo** [comment]
What PyTorch version are you using? How did you install tiny-cuda-nn?

**Comment by bennyguo** [comment]
What GPU are you using? It seems that tiny-cuda-nn is compiled with an sm_61 GPU.

I suggest you open an issue in the [original tiny-cuda-nn repo](https://github.com/NVlabs/tiny-cuda-nn) and see if they have some problems supporting old GPUs.

**Comment by sunshineywz123** [comment]
> 
![image](https://user-images.githubusercontent.com/32233542/200168485-d5b6703f-5f73-4399-84b2-2acb76a8bee8.png)
GeForce RTX 208..

**Comment by bennyguo** [comment]
You may need to check the CUDA compiler version by `nvcc -V`, and make sure it's consistent with the installed torch wheel.

**Comment by sunshineywz123** [comment]
> You may need to check the CUDA compiler version by `nvcc -V`, and make sure it's consistent with the installed torch wheel.

I can't install nvcc in my environment, can you provide a google colab project for us to test? Or is there any other means to confirm the environment besides nvcc?

**Comment by bennyguo** [comment]
nvcc is shipped with your CUDA installation. If you use Anaconda to install PyTorch, a corresponding CUDA Toolkit is automatically installed by Anaconda. You may use the following command to find the CUDA installation path:
```
sudo find / -name nvcc
```
After that, you may update your $PATH and $LD_LIBRARY_PATH to this CUDA installation and re-install tiny-cuda-nn.

**Comment by sunshineywz123** [comment]
> nvcc is shipped with your CUDA installation. If you use Anaconda to install PyTorch, a corresponding CUDA Toolkit is automatically installed by Anaconda. You may use the following command to find the CUDA installation path:
> 
> ```
> sudo find / -name nvcc
> ```
> 
> After that, you may update your $PATH and $LD_LIBRARY_PATH to this CUDA installation and re-install tiny-cuda-nn.

 nvcc -V
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2020 NVIDIA Corporation
Built on Tue_Sep_15_19:10:02_PDT_2020
Cuda compilation tools, release 11.1, V11.1.74
Build cuda_11.1.TC455_06.29069683_0

**Comment by bennyguo** [comment]
Where is this nvcc located? Is it Anaconda-installed?

When installing PyTorch using Anaconda, what CUDA version did you specify?

**Comment by sunshineywz123** [comment]
> Where is this nvcc located? Is it Anaconda-installed?
> 
> When installing PyTorch using Anaconda, what CUDA version did you specify?

which nvcc
/usr/local/cuda/bin/nvcc

**Comment by bennyguo** [comment]
Maybe you could try installing torch1.10.1 with CUDA11.3:
```
conda install pytorch==1.10.1 torchvision==0.11.2 torchaudio==0.10.1 cudatoolkit=11.3 -c pytorch -c conda-forge
```
Then re-install tiny-cuda-nn.
