### ISSUE TITLE
Texture mesh quality is not good, how to adjust

### ISSUE THREAD

**Issue by nangongliufeng** [bennyguo/instant-nsr-pl#70]
![图片](https://user-images.githubusercontent.com/87115602/235671042-0e35da2d-7afd-4e4c-a725-409f9f6d4018.png)

**Comment by bennyguo** [comment]
I think this is probably related to https://github.com/bennyguo/instant-nsr-pl/issues/60. Could you try training without view-dependent color as demonstrated [here](https://github.com/bennyguo/instant-nsr-pl/issues/60#issuecomment-1515214611) and see how it comes out?
