### ISSUE TITLE
issue when training on colmap data

### ISSUE THREAD

**Issue by huang997733** [bennyguo/instant-nsr-pl#82]
Hi there,

I have encountered this issue when training on colmap data (neus-colmap and nerf-colmap)

`RuntimeError: indices should be either on cpu or on the same device as the indexed tensor (cpu)`

This error message shows up when the training process hits 5000 iterations
I have searched online but nothing really helpful
Any ideas how to solve this issue?

Thanks so much!

**Comment by Yellowshuohahaha** [comment]
> Hi there,
> 
> I have encountered this issue when training on colmap data (neus-colmap and nerf-colmap)
> 
> `RuntimeError: indices should be either on cpu or on the same device as the indexed tensor (cpu)`
> 
> This error message shows up when the training process hits 5000 iterations I have searched online but nothing really helpful Any ideas how to solve this issue?
> 
> Thanks so much!

I have the same problem. Have you solved it?

**Comment by huang997733** [comment]
> > Hi there,
> > I have encountered this issue when training on colmap data (neus-colmap and nerf-colmap)
> > `RuntimeError: indices should be either on cpu or on the same device as the indexed tensor (cpu)`
> > This error message shows up when the training process hits 5000 iterations I have searched online but nothing really helpful Any ideas how to solve this issue?
> > Thanks so much!
> 
> I have the same problem. Have you solved it?

This is because the dataset is not loaded on gpu, simply change `load_data_on_gpu` in `configs/neus-colmap.yaml` to true would fix the problem.
It took me several hours to find out lol.

**Comment by KeKer7** [comment]
Can you train Neus on the Colmap dataset and achieve good results? I can't render it on the mip nerf dataset and tTAT dataset, it always doesn't converge
