### ISSUE TITLE
Integrate numerical gradients in Neus based on the paper of Neuralangelo

### ISSUE THREAD

**Issue by xiaohulihutu** [bennyguo/instant-nsr-pl#84]
Hi there,

Just found this paper, do you have any plan to optimize the analytical gradient to the numerical gradient? This should help minimize the cavity issue.

https://d1qx31qr3h6wln.cloudfront.net/publications/Li_Neuralangelo_High-Fidelity_Neural_Surface_Reconstruction_CVPR_2023_paper.pdf

![image](https://github.com/bennyguo/instant-nsr-pl/assets/25570249/b81bb919-a6f4-473d-a194-75a01e5e9167)

**Comment by bennyguo** [comment]
Same as https://github.com/bennyguo/instant-nsr-pl/issues/83. I'll integrate this feature soon after some experiments.

**Comment by xiaohulihutu** [comment]
Yep, I just saw #83, i will close this for now and check update on 83
